include:
  - path: infra/airflow/docker-compose.yaml
    env_file:
      - .env.global
      - infra/airflow/.env

services:
  api:
    build:
      context: . # to allow copying the pyproject.toml
      dockerfile: api/Dockerfile
    volumes:
      - ./api/src:/workspace/src
    # don't start if overfast api hasn't started yet
    depends_on:
      mongodb:
        condition: service_started
    networks:
      - lol_api_network

    # checking service is up every 5 seconds
   
    healthcheck:
      test: ["CMD-SHELL", "curl http://0.0.0.0:8080/health || exit 1"]
      interval: 60s
      timeout: 5s
    env_file:
      - .env.global
      - ./api/.env
    # scrape every week
    # healthcheck:
    #   test: ["CMD-SHELL", "curl http://0.0.0.0:8080/scrape || exit 1"]
    #   interval: 10080s # 1 week
    #   timeout: 60s
    
  mongodb:
    build: infra/mongodb
    ports:
      - "27017:27017"
    # volumes:
      # - ./data/db:/data/db
    env_file:
      - .env.global
    networks:
      - lol_api_network

  postgres:
    build: infra/postgres
    ports:
      - 5555:5432
    env_file:
      - .env.global
      - ./infra/postgres/.env
    networks:
      - lol_api_network

  nginx:
    build: ./infra/nginx
    ports:
      - 80:80
    depends_on:
      api:
        condition: service_started
    networks:
      - lol_api_network

networks:
  lol_api_network:
    driver: bridge
