name: CI
on:
  pull_request:
    branches:
      - '**'
    paths:
      - '**/*.py' # if a python file changed
      - '.pylintrc' # if changed the linter's rules


jobs:
  pylint:
    runs-on: ubuntu-22.04
    strategy:
      # to allow several python version (airflow, api, etc.)
      matrix:
        python-version:
          - 3.13
    container:
      image: python:${{ matrix.python-version }}-alpine3.22
    permissions:
      contents: write
    steps:
      - name: Initial checkout
        uses: actions/checkout@v4

      - name: Install uv
        run: apk add curl && curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Install dependencies
        run: |
          uv sync --extra linter

      - name: Run linter
        run: |
          uv run ruff check . --select=E231 --fix --preview
          find . -name '*.py' | grep -v .venv | xargs uv run pylint --rcfile=.pylintrc

      - name: Update branch with linter changes
        run: |
          if  ! $ACT ; then
          if ! git diff --quiet; then
            git config --global user.name "github-actions[bot]"
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git add -u
            git diff --quiet && git diff --staged --quiet || git commit -m "fix: auto-fix spacing after commas"
            git push origin HEAD:$(git branch --show-current)
          else
            echo "All good."
          fi
          fi

  api-tests:
    needs: pylint
    runs-on: ubuntu-22.04
    strategy:
      # to allow several python version (airflow, api, etc.)
      matrix:
        python-version:
          - 3.13
    container:
      image: python:${{ matrix.python-version }}-alpine3.22
    steps:
      - name: Initial checkout
        uses: actions/checkout@v4

      - name: Install uv
        run: apk add curl && curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Install dependencies
        run: |
          uv sync --extra test --extra api

      - name: Run tests
        run: uv run pytest api/src/tests
