name: CI
on:
  pull_request:
    branches:
      - '**'
    paths:
      - '**/*.py' # if a python file changed
      - '.pylintrc' # if changed the linter's rules


jobs:
  pylint:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Initial checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }} # comment this line when running locally

      - name: Setup python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install pylint ruff

      - name: Run linter
        run: |
          ruff check . --select=E231 --fix --preview
          find . -name '*.py' | xargs pylint --rcfile=.pylintrc

      - name: Update branch with linter changes
        run: |
          if  ! $ACT ; then
          if ! git diff --quiet; then
            git config --global user.name "github-actions[bot]"
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git add -u
            git diff --quiet && git diff --staged --quiet || git commit -m "fix: auto-fix spacing after commas"
            git push origin HEAD:$(git branch --show-current)
          else
            echo "All good."
          fi
          fi

  api-tests:
    needs: pylint
    runs-on: ubuntu-22.04
    env:
      RIOT_API_KEY: ${{ secrets.RIOT_API_KEY }}
      MONGODB_URL: ${{ secrets.MONGODB_URL }}
      POSTGRES_DB_URL: ${{ secrets.POSTGRES_DB_URL }}
    container:
      image: python:3.13-alpine3.22
    steps:
      - name: Initial checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          python3 -m pip install -r api/requirements.txt

      - name: Run tests
        run: pytest
        working-directory: api/src/tests
